Fix timer
rust-amplify/io-reactor pull request #16
Opened 2023-01-26 14:41 UTC by dr-orlovsky

2023-01-26 19:11 UTC, dr-orlovsky commented on src/reactor.rs
> +
Done

2023-01-26 20:00 UTC, cloudhead approved these changes
LGTM

2023-01-26 20:01 UTC, cloudhead commented
I can try testing it before you merge, if you want.

2023-01-26 20:08 UTC, cloudhead commented
Ok it's still not working correctly. My hunch is that the timeout you're passing to `poll` is not correct, because the `Duration` type is being used for both absolute and relative time. When you get a timeout out of `TimeoutManager::next`, it's a unix time (absolute), but the `poll()` function expects a relative time to wait. Instead, it's getting a huge duration. So I guess you need to substract `before_poll`.

2023-01-26 20:08 UTC, cloudhead requested changes
See latest comment!

2023-01-27 11:43 UTC, dr-orlovsky commented
@cloudhead did a quickfix

2023-02-21 12:43 UTC, merged

2023-02-21 12:48 UTC, dr-orlovsky commented
Merged & released `v0.1.1`